<a href="https://colab.research.google.com/github/gg5d/DS-1002/blob/main/pandas3_student_F23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas III


### University of Virginia
### DS 1002: Programming for Data Science
---  


### PREREQUISITES
- variables
- data types
- operators
- list comprehensions (not essential)
- numpy arrays (not essential)
- pandas DataFrames I


### SOURCES
- ten minutes to pandas  
https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html


- pivot_table()  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html


- concat()  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html


- merge()  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html


- get_dummies()  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html



### OBJECTIVES
- Introduce more advanced pandas dataframe operations for data munging



### CONCEPTS

- DataFrame
- apply()
- aggregation using split-apply-combine
- pivot_table()
- groupby()
- concat()
- merging/joining dataframes with merge(), concat()
- reshaping data
- dummy coding categorical data


---

## Additional Pandas DataFrame Functionality

Pandas DataFrames I covered creating, modifying, and subsetting DataFrames, among other topics.  
These notes will demonstrate further methods for data munging and analysis.

In [ ]:
import numpy as np
import pandas as pd

#### Load Iris

In [ ]:
import seaborn as sns

iris = sns.load_dataset('iris')

In [ ]:
iris.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Apply Lambda Functions with `.apply()`

Apply a transformation to each record. Uses a `lambda` function.

sepal_length  sepal_width  petal_length  petal_width species  sepal_len_sq
0           5.1          3.5           1.4          0.2  setosa         26.01
1           4.9          3.0           1.4          0.2  setosa         24.01
2           4.7          3.2           1.3          0.2  setosa         22.09
3           4.6          3.1           1.5          0.2  setosa         21.16
4           5.0          3.6           1.4          0.2  setosa         25.00

Transformation involving multiple columns. Uses `axis=1` to access columns.  
Compute average of `sepal_length`, `sepal_width`:

sepal_length  sepal_width  petal_length  petal_width species  sepal_len_sq  \
0           5.1          3.5           1.4          0.2  setosa         26.01   
1           4.9          3.0           1.4          0.2  setosa         24.01   
2           4.7          3.2           1.3          0.2  setosa         22.09   
3           4.6          3.1           1.5          0.2  setosa         21.16   
4           5.0          3.6           1.4          0.2  setosa         25.00   

   sepal_len_wid_avg  
0               4.30  
1               3.95  
2               3.95  
3               3.85  
4               4.30

### TRY FOR YOURSELF (UNGRADED EXERCISES)

1) Use `apply()` to append a new column that is the minimum of (petal_length, petal_width)

Print the head, tail of the new dataframe to check things look correct.

In [ ]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  sepal_len_sq  \
0           5.1          3.5           1.4          0.2  setosa         26.01   
1           4.9          3.0           1.4          0.2  setosa         24.01   
2           4.7          3.2           1.3          0.2  setosa         22.09   
3           4.6          3.1           1.5          0.2  setosa         21.16   
4           5.0          3.6           1.4          0.2  setosa         25.00   

   sepal_len_wid_avg  min_petal  
0               4.30        0.2  
1               3.95        0.2  
2               3.95        0.2  
3               3.85        0.2  
4               4.30        0.2

In [ ]:
iris.tail()

sepal_length  sepal_width  petal_length  petal_width    species  \
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     sepal_len_sq  sepal_len_wid_avg  min_petal  
145         44.89               4.85        2.3  
146         39.69               4.40        1.9  
147         42.25               4.75        2.0  
148         38.44               4.80        2.3  
149         34.81               4.45        1.8

## Aggregation

Involves one or more of:

- splitting the data into groups
- applying a function to each group
- combining results

### `.groupby()`

Compute mean of each column, grouped (separately) by species

sepal_length  sepal_width  petal_length  petal_width  \
species                                                            
setosa             5.006        3.428         1.462        0.246   
versicolor         5.936        2.770         4.260        1.326   
virginica          6.588        2.974         5.552        2.026   

            sepal_len_sq  sepal_len_wid_avg  min_petal  
species                                                 
setosa           25.1818              4.217      0.246  
versicolor       35.4972              4.353      1.326  
virginica        43.7980              4.781      2.026

### `pd.pivot_table()`

A pivot table is a table of values which are aggregations of groups of individual values of a more extensive table

Apply a function `aggfunc` to selected values grouped by columns

[Details](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html)

Compute mean sepal length for each species:

species       setosa  versicolor  virginica
sepal_length   5.006       5.936      6.588

### TRY FOR YOURSELF (UNGRADED EXERCISES)

2) Use a pivot table to compute the following statistics on sepal_width and petal_width grouped by species:

- median  
- mean

These can be computed together in a single call to `pivot_table()`.

species             setosa  versicolor  virginica
petal_width mean     0.246       1.326      2.026
            median   0.200       1.300      2.000
sepal_width mean     3.428       2.770      2.974
            median   3.400       2.800      3.000

## Stacking and Unstacking

Similar to pivoting, but requires -- and takes advantage of -- indexes.

In [ ]:
iris_w_idx = iris.copy()

# Give the original index a name
iris_w_idx.index.name = 'obs_id'

# Create a multi-index, using `species` as part of the key.
iris_w_idx = iris_w_idx.reset_index().set_index(['species','obs_id'])

In [ ]:
iris_w_idx

sepal_length  sepal_width  petal_length  petal_width  \
species   obs_id                                                         
setosa    0                5.1          3.5           1.4          0.2   
          1                4.9          3.0           1.4          0.2   
          2                4.7          3.2           1.3          0.2   
          3                4.6          3.1           1.5          0.2   
          4                5.0          3.6           1.4          0.2   
...                        ...          ...           ...          ...   
virginica 145              6.7          3.0           5.2          2.3   
          146              6.3          2.5           5.0          1.9   
          147              6.5          3.0           5.2          2.0   
          148              6.2          3.4           5.4          2.3   
          149              5.9          3.0           5.1          1.8   

                  sepal_len_sq  sepal_len_wid_avg  min_petal  
species   obs_id                                              
setosa    0              26.01               4.30        0.2  
          1              24.01               3.95        0.2  
          2              22.09               3.95        0.2  
          3              21.16               3.85        0.2  
          4              25.00               4.30        0.2  
...                        ...                ...        ...  
virginica 145            44.89               4.85        2.3  
          146            39.69               4.40        1.9  
          147            42.25               4.75        2.0  
          148            38.44               4.80        2.3  
          149            34.81               4.45        1.8  

[150 rows x 7 columns]

## `.unstack()`

[Details](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html)

In [ ]:
iris_wide

species  setosa  versicolor  virginica
obs_id                                
0           5.1         0.0        0.0
1           4.9         0.0        0.0
2           4.7         0.0        0.0
3           4.6         0.0        0.0
4           5.0         0.0        0.0
...         ...         ...        ...
145         0.0         0.0        6.7
146         0.0         0.0        6.3
147         0.0         0.0        6.5
148         0.0         0.0        6.2
149         0.0         0.0        5.9

[150 rows x 3 columns]

## `.stack()`

Return a reshaped DataFrame or Series having a multi-level index with one or more new inner-most levels compared to the current DataFrame. The new inner-most levels are created by pivoting the columns of the current dataframe:

[Details](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html)

sepal_length
species   obs_id              
setosa    0                5.1
          1                4.9
          2                4.7
          3                4.6
          4                5.0
...                        ...
virginica 145              6.7
          146              6.3
          147              6.5
          148              6.2
          149              5.9

[450 rows x 1 columns]

## Combining DataFrames


### `pd.concat()`  

Concatenate pandas objects along an axis

[Details](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html)

Create two dfs and vertically stack them

In [ ]:
df1 = pd.DataFrame(np.random.randn(3, 4))
df2 = pd.DataFrame(np.random.randn(3, 4))

print(df1)
print('-'*45)
print(df2)

          0         1         2         3
0  0.392107  0.509639  0.979242 -1.027487
1 -0.121717 -0.140941  1.000550  0.425382
2  0.081751  0.183288  0.657083 -0.273045
---------------------------------------------
          0         1         2         3
0 -0.024622  0.334710  0.000306  0.681266
1  1.107880  0.568124  1.087857  0.080963
2  0.637418 -0.520785 -0.043940 -0.185343


In [ ]:
df3 =

# print('-'*45)
print(df3)

          0         1         2         3
0  0.392107  0.509639  0.979242 -1.027487
1 -0.121717 -0.140941  1.000550  0.425382
2  0.081751  0.183288  0.657083 -0.273045
0 -0.024622  0.334710  0.000306  0.681266
1  1.107880  0.568124  1.087857  0.080963
2  0.637418 -0.520785 -0.043940 -0.185343


**Concat columns**  
This assumes that the indexes represent IDs of specific things or events

In [ ]:
df4 =

df4

foo                                     bar                      \
          0         1         2         3         0         1         2   
0 -0.825220 -0.102500 -0.510075 -0.953772 -1.034678 -0.054963 -0.670725   
1  0.490151  0.101113 -1.766722 -0.557258 -0.246691  0.111340  0.266434   
2 -0.543623 -0.152922 -0.234991  1.652197  0.492420 -1.879829  0.511996   

             
          3  
0  1.142413  
1  0.097658  
2  1.164628

In [ ]:
df4.foo

0         1         2         3
0 -0.825220 -0.102500 -0.510075 -0.953772
1  0.490151  0.101113 -1.766722 -0.557258
2 -0.543623 -0.152922 -0.234991  1.652197

In [ ]:
df4.bar

0         1         2         3
0 -1.034678 -0.054963 -0.670725  1.142413
1 -0.246691  0.111340  0.266434  0.097658
2  0.492420 -1.879829  0.511996  1.164628

### `merge()`

SQL-style joining of tables (DataFrames)

Important parameters include:

- `how` : type of merge {'left', 'right', 'outer', 'inner', 'cross'}, default ‘inner’

Type of merge to be performed.
* left: use only keys from left frame, similar to a SQL left outer join; preserve key order.
* right: use only keys from right frame, similar to a SQL right outer join; preserve key order.
* outer: use union of keys from both frames, similar to a SQL full outer join; sort keys lexicographically.
* inner: use intersection of keys from both frames, similar to a SQL inner join; preserve the order of the left keys.
* cross: creates the cartesian product from both frames, preserves the order of the left keys.

- `on`  : Column or index level names to join on.

        
[Details](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html)

Create two tables, `left` and `right`. Then right join them on `key`.  
Right join means include all records from table on right.  
The `key` is used for matching up the records.

In [ ]:
left = pd.DataFrame({"key": ["jamie", "bill"], "lval": [15, 22]})
right = pd.DataFrame({"key": ["jamie", "bill", "asher"], "rval": [4, 5, 8]})
print('---left')
print(left)
print('\n---right')
print(right)

---left
     key  lval
0  jamie    15
1   bill    22

---right
     key  rval
0  jamie     4
1   bill     5
2  asher     8


In [ ]:
joined =


print('\n---joined')
print(joined)


---joined
     key  lval  rval
0  jamie  15.0     4
1   bill  22.0     5
2  asher   NaN     8


Notice the NaN inserted into the record with key=asher, since the left table didn't contain the key.

**Matching column names**  
In this next example, the value columns have the same name: *val*.  Notice what happens to the column names.

In [ ]:
left = pd.DataFrame({"key": ["jamie", "bill"], "val": [15, 22]})
right = pd.DataFrame({"key": ["jamie", "bill", "asher"], "val": [4, 5, 8]})
print('---left')
print(left)
print('\n---right')
print(right)

---left
     key  val
0  jamie   15
1   bill   22

---right
     key  val
0  jamie    4
1   bill    5
2  asher    8


In [ ]:
joined =


print('\n---joined')
print(joined)


---joined
     key  val_x  val_y
0  jamie   15.0      4
1   bill   22.0      5
2  asher    NaN      8


## `.join()`

An SQL-like joiner, but this one takes advantage of indexes.

Join columns of another DataFrame.

Join columns with other DataFrame either on index or on a key column. Efficiently join multiple DataFrame objects by index at once by passing a list.

Give our dataframes indexes and distinctive columns names.

[Details](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html)

In [ ]:
left2 = left.set_index('key').rename(columns={'val':'val_1'})
right2 = right.set_index('key').rename(columns={'val':'val_2'})

In [ ]:
left2

val_1
key         
jamie     15
bill      22

In [ ]:
right2

val_2
key         
jamie      4
bill       5
asher      8

In [ ]:
right2.join(left2) # defaults to 'inner'

val_2  val_1
key                
jamie      4   15.0
bill       5   22.0
asher      8    NaN

In [ ]:
right2.join(left2, how = 'left')

val_2  val_1
key                
jamie      4   15.0
bill       5   22.0
asher      8    NaN

## Summary

* Use **join** if you have shared indexes
* Use **merge** if you do not have shared indexes
* Use **concat** to combine based on shared indexes or columns

### TRY FOR YOURSELF (UNGRADED EXERCISES)

3) Redo the join exercise above, using an inner join instead of a right join.  
Make sure the results make sense.

In [ ]:
left = pd.DataFrame({"key": ["jamie", "bill"], "lval": [15, 22]})
right = pd.DataFrame({"key": ["jamie", "bill", "asher"], "rval": [4, 5, 8]})

print('---left')
print(left)
print('\n---right')
print(right)

---left
     key  lval
0  jamie    15
1   bill    22

---right
     key  rval
0  jamie     4
1   bill     5
2  asher     8


In [ ]:
joined =


print('\n---joined')
print(joined)


---joined
     key  lval  rval
0  jamie    15     4
1   bill    22     5


## `.reshape()`

Changes the object's shape

We illustrate creating pandas Series, extracting array of length 6, and reshaping to 3x2 array.

In [ ]:
# create a series
ser = pd.Series([1, 1, 2, 3, 5, 8])

# extract values
vals = ser.values

print('orig data:', vals)
print('orig type:', type(vals))
print('orig shape:', vals.shape)

orig data: [1 1 2 3 5 8]
orig type: <class 'numpy.ndarray'>
orig shape: (6,)


In [ ]:
# reshaping series
reshaped_vals = vals.reshape((3, 2))

print('\n reshaped vals:')
print(reshaped_vals)
print('\n new type:', type(reshaped_vals))
print('new shape:', reshaped_vals.shape)


 reshaped vals:
[[1 1]
 [2 3]
 [5 8]]

 new type: <class 'numpy.ndarray'>
new shape: (3, 2)


Including -1 as one of the dimensions tells numpy: infer this dimension from the data and the other dimensions.

Example: enforce 3 columns:

In [ ]:
vals.reshape(-1,3)

array([[1, 1, 2],
       [3, 5, 8]])

Enforce 3 rows:

In [ ]:
vals.reshape(3,-1)

array([[1, 1],
       [2, 3],
       [5, 8]])

**IMPORTANT NOTE**  

Notice the shape of original array: `(6,)`  
This is a vector with one dimension, and is different from two-dimensional `(6,1)` array

### TRY FOR YOURSELF (UNGRADED EXERCISES)

4) Recreate the series from above with data [1, 1, 2, 3, 5, 8]  
Extract the data from the series and reshape to 2x3.  
Print both the reshaped data, and the dimensions.

[[1 1 2]
 [3 5 8]]
new shape: (2, 3)


## Categoricals

Categorical data takes discrete values where computation on the values does not make sense.  
Zip code is a typical example.

To include categoricals in models, they must be converted to numeric.  

### `get_dummies()`
Dummy code categorical data

Important parameters:

- `prefix`    : append prefix to column names (a good idea for later use)
- `drop_first`: remove first level, as only `k-1` variables needed to represent `k` levels

[Details](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html)

In [ ]:
cats = pd.DataFrame({'breed':['persian','persian','siamese','himalayan','burmese']})

print('--categorical data')
print(cats)

--categorical data
       breed
0    persian
1    persian
2    siamese
3  himalayan
4    burmese


In [ ]:
cats = pd.get_dummies(cats.breed, drop_first=True, prefix='breed', dtype=int)

print('\n')
print('--dummified categorical data')
print(cats)



--dummified categorical data
   breed_himalayan  breed_persian  breed_siamese
0                0              1              0
1                0              1              0
2                0              0              1
3                1              0              0
4                0              0              0


Notice `burmese` was dropped (first level by alphabet)

### TRY FOR YOURSELF (UNGRADED EXERCISES)

5) The dataframe below contains two categoricals. Dummify each of them, giving them a prefix and dropping the first level from each.

Print the new dataframe to insure correctness.

Hint: You might want to dummify each column into separate new dataframes, and then merge them together by using:

`pd.concat([df1, df2], axis=1)`

In [ ]:
cats2 = pd.DataFrame({'breed':['persian','persian','siamese','himalayan','burmese'],
                      'color':['calico','white','seal point','cream','sable']})

breed__himalayan  breed__persian  breed__siamese  color__cream  \
0             False            True           False         False   
1             False            True           False         False   
2             False           False            True         False   
3              True           False           False          True   
4             False           False           False         False   

   color__sable  color__seal point  color__white  
0         False              False         False  
1         False              False          True  
2         False               True         False  
3         False              False         False  
4          True              False         False

---